### ISSUE TITLE
How can I use just Phone Number Login? 

### ISSUE THREAD

**Issue by ketanchoyal** [gildaswise/flutter_phone_auth#5]
I don't want the user to enter email id every time they login

**Comment by gildaswise** [comment]
Start by changing `AuthStatus.PROFILE_AUTH` to `AuthStatus.PHONE_AUTH`, then the user won't be required to use their Google Account to proceed. Then, instead of `linkWithCredential`, change to `signInWithCredential`; after, just take out everything from the `_linkWithPhoneNumber` function, and do your thing there!
